# 🚀 Lab 13: Filtering, Sorting, and Merging DataFrames

### 📘 Lab Overview
In this lab, you will learn how to filter rows in Pandas DataFrames using conditions, sort data by one or more columns, and merge multiple DataFrames using common keys. These are core data manipulation skills used in data analysis, reporting, machine learning preparation, and business intelligence workflows.

You will work with realistic hospital and location datasets, then combine filtering, sorting, and merging into a full data analysis pipeline. By the end of the lab, you will be able to prepare and organize tabular data more effectively for deeper analysis.

### 🎯 Objectives
By the end of this lab, you will be able to:
*   Filter DataFrame rows based on specific conditions using boolean indexing.
*   Sort DataFrame values by single and multiple columns.
*   Merge separate CSV files using common columns (Joins).
*   Apply conditional filtering with multiple criteria using logical operators.
*   Understand different types of joins (Inner, Left, Right, Outer).
*   Clean and prepare data through integrated pipelines.

### 🧰 Prerequisites
*   Basic Python (variables, lists).
*   Familiarity with Pandas fundamentals.
*   Understanding of CSV structures and basic data types.

### 💡 ELI10: What are we doing?
Imagine you have a giant pile of index cards about hospitals.
1. **Filtering** is like picking out only the cards for 'Children's Hospitals'.
2. **Sorting** is like putting those cards in order from the biggest hospital to the smallest.
3. **Merging** is like taking a second pile of cards with addresses and taping them to the back of the hospital cards so you have all the info in one place!

## ⚙️ Environment Setup
We start by importing the tools we need. Pandas is our primary library for data tables.

In [1]:
import pandas as pd
import numpy as np
import warnings
import os

# Ignore unnecessary warnings to keep the output clean
warnings.filterwarnings('ignore')

# Display all columns and rows for better visibility in Colab
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

print("Environment setup complete!")

Environment setup complete!

## 📥 Creating and Loading Data
Before we can analyze data, we need data! We will create two datasets: one with hospital details and one with their locations.

In [2]:
# Subtask 1.2: Create Sample Hospital Data

# Define the hospital information
hospital_data = {
    'hospital_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'hospital_name': ['City General Hospital', 'St. Mary Medical Center', 'Regional Health System', 'Community Hospital', 'University Medical Center', 'Memorial Hospital', 'Sacred Heart Hospital', 'Metro General'],
    'bed_count': [450, 320, 680, 180, 520, 290, 410, 380],
    'patient_satisfaction': [4.2, 4.7, 3.9, 4.5, 4.1, 4.8, 4.3, 3.8],
    'emergency_services': [True, True, True, False, True, True, True, True],
    'specialty': ['General', 'Cardiac', 'Trauma', 'Pediatric', 'Research', 'Geriatric', 'Cardiac', 'General']
}

# Define the location information mapped by hospital_id
location_data = {
    'hospital_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego'],
    'state': ['NY', 'CA', 'IL', 'TX', 'AZ', 'PA', 'TX', 'CA'],
    'zip_code': ['10001', '90210', '60601', '77001', '85001', '19101', '78201', '92101'],
    'region': ['Northeast', 'West', 'Midwest', 'South', 'West', 'Northeast', 'South', 'West']
}

# Create Pandas DataFrames from dictionaries
hospitals_df = pd.DataFrame(hospital_data)
locations_df = pd.DataFrame(location_data)

# Save these to CSV files so we can practice loading them
hospitals_df.to_csv('hospitals.csv', index=False)
locations_df.to_csv('locations.csv', index=False)

print("Sample CSV files created successfully!")

Sample CSV files created successfully!

In [3]:
# Subtask 1.3: Load CSV Files

# Reading the files we just created
hospitals = pd.read_csv('hospitals.csv')
locations = pd.read_csv('locations.csv')

print("Hospitals Dataset Loaded:")
display(hospitals.head(3))

print("\nLocations Dataset Loaded:")
display(locations.head(3))

Hospitals Dataset Loaded:

,hospital_id,hospital_name,bed_count,patient_satisfaction,emergency_services,specialty
0,1,City General Hospital,450,4.2,True,General
1,2,St. Mary Medical Center,320,4.7,True,Cardiac
2,3,Regional Health System,680,3.9,True,Trauma

Locations Dataset Loaded:

   hospital_id         city state  zip_code     region
0            1     New York    NY     10001  Northeast
1            2  Los Angeles    CA     90210       West
2            3      Chicago    IL     60601    Midwest

## 🔎 Filtering Data
### 💡 ELI10: Filtering
Filtering is like using a sieve. You set a rule (like "only show hospitals with > 400 beds") and Pandas throws away everything that doesn't fit.

In [4]:
# Subtask 2.1 & 2.2: Basic and Multiple Condition Filtering

# 1. Single Condition: Large hospitals
large_hospitals = hospitals[hospitals['bed_count'] > 400]
print("Hospitals with > 400 beds:")
display(large_hospitals[['hospital_name', 'bed_count']])

# 2. Multiple Conditions using '&' (AND)
# We use parentheses () around each condition to avoid errors
large_emergency = hospitals[
    (hospitals['bed_count'] > 300) &
    (hospitals['emergency_services'] == True)
]
print("\nLarge hospitals with emergency services:")
display(large_emergency[['hospital_name', 'bed_count', 'emergency_services']])

Hospitals with > 400 beds:

               hospital_name  bed_count
0      City General Hospital        450
2     Regional Health System        680
4  University Medical Center        520
6      Sacred Heart Hospital        410

Large hospitals with emergency services:

               hospital_name  bed_count  emergency_services
0      City General Hospital        450                True
1    St. Mary Medical Center        320                True
2     Regional Health System        680                True
4  University Medical Center        520                True
6      Sacred Heart Hospital        410                True
7              Metro General        380                True

In [5]:
# Subtask 2.3: String-Based Filtering

# Filtering using string methods
general_hospitals = hospitals[hospitals['hospital_name'].str.contains('General', na=False)]
print("Hospitals with 'General' in the name:")
display(general_hospitals[['hospital_name']])

# Using .isin() for multiple categories
cardiac_trauma = hospitals[hospitals['specialty'].isin(['Cardiac', 'Trauma'])]
print("\nCardiac and Trauma specialty hospitals:")
display(cardiac_trauma[['hospital_name', 'specialty']])

Hospitals with 'General' in the name:

           hospital_name
0  City General Hospital
7          Metro General

Cardiac and Trauma specialty hospitals:

             hospital_name specialty
1  St. Mary Medical Center   Cardiac
2   Regional Health System    Trauma
6    Sacred Heart Hospital   Cardiac

## ↕️ Sorting Data
### 💡 ELI10: Sorting
Sorting is just putting things in order, like organizing your bookshelf by height or by the author's name.

In [6]:
# Subtask 3.1 & 3.2: Single and Multiple Column Sorting

# Sort by bed count (highest first)
sorted_by_beds = hospitals.sort_values('bed_count', ascending=False)
print("Hospitals by size (descending):")
display(sorted_by_beds[['hospital_name', 'bed_count']])

# Sort by specialty (A-Z) AND then satisfaction (highest first)
sorted_mixed = hospitals.sort_values(
    ['specialty', 'patient_satisfaction'],
    ascending=[True, False]
)
print("\nSorted by Specialty (Asc) and Satisfaction (Desc):")
display(sorted_mixed[['hospital_name', 'specialty', 'patient_satisfaction']])

Hospitals by size (descending):

               hospital_name  bed_count
2     Regional Health System        680
4  University Medical Center        520
0      City General Hospital        450
6      Sacred Heart Hospital        410
7              Metro General        380
1    St. Mary Medical Center        320
5          Memorial Hospital        290
3         Community Hospital        180

Sorted by Specialty (Asc) and Satisfaction (Desc):

               hospital_name  specialty  patient_satisfaction
1    St. Mary Medical Center    Cardiac                   4.7
6      Sacred Heart Hospital    Cardiac                   4.3
0      City General Hospital    General                   4.2
7              Metro General    General                   3.8
5          Memorial Hospital  Geriatric                   4.8
3         Community Hospital  Pediatric                   4.5
4  University Medical Center   Research                   4.1
2     Regional Health System     Trauma                   3.9

## 🔗 Merging DataFrames
### 💡 ELI10: Merging (Joins)
Merging is like a puzzle. We use a 'Key' (like `hospital_id`) to connect two different tables together.
*   **Inner**: Only keep rows where the ID is in BOTH tables.
*   **Left**: Keep everything from the first table, add info from the second if it exists.
*   **Outer**: Keep everything from everywhere!

In [7]:
# Task 4: Merging DataFrames

# Inner Join: Combine hospitals and locations based on 'hospital_id'
inner_merged = pd.merge(hospitals, locations, on='hospital_id')
print("Inner Join Result (Hospitals + Locations):")
display(inner_merged[['hospital_name', 'city', 'state', 'region']])

# Merge with Suffixes (Handling overlapping column names)
# Let's create a conflict by adding a 'hospital_name' column to locations
locations_conflict = locations.copy()
locations_conflict['hospital_name'] = locations_conflict['city'] + " Branch"

# Use suffixes to distinguish which 'hospital_name' came from which table
merged_suffixes = pd.merge(
    hospitals,
    locations_conflict,
    on='hospital_id',
    suffixes=('_orig', '_loc_alias')
)
print("\nMerge with Suffixes:")
display(merged_suffixes[['hospital_name_orig', 'hospital_name_loc_alias', 'city']])

Inner Join Result (Hospitals + Locations):

               hospital_name          city state     region
0      City General Hospital      New York    NY  Northeast
1    St. Mary Medical Center   Los Angeles    CA       West
2     Regional Health System       Chicago    IL    Midwest
3         Community Hospital       Houston    TX      South
4  University Medical Center       Phoenix    AZ       West
5          Memorial Hospital  Philadelphia    PA  Northeast
6      Sacred Heart Hospital   San Antonio    TX      South
7              Metro General     San Diego    CA       West

Merge with Suffixes:

          hospital_name_orig hospital_name_loc_alias          city
0      City General Hospital         New York Branch      New York
1    St. Mary Medical Center      Los Angeles Branch   Los Angeles
2     Regional Health System          Chicago Branch       Chicago
3         Community Hospital          Houston Branch       Houston
4  University Medical Center          Phoenix Branch       Phoenix
5          Memorial Hospital     Philadelphia Branch  Philadelphia
6      Sacred Heart Hospital      San Antonio Branch   San Antonio
7              Metro General        San Diego Branch     San Diego

## 🧪 Full Analysis Pipeline
Now we combine everything: Merge the data, Filter for specific regions, and Sort by satisfaction.

In [8]:
# Step 1: Merge everything
complete_data = pd.merge(hospitals, locations, on='hospital_id')

# Step 2: Filter and Sort
# We want Large hospitals (>300 beds) in West/Northeast with emergency services
final_report = complete_data[
    (complete_data['bed_count'] > 300) &
    (complete_data['emergency_services'] == True) &
    (complete_data['region'].isin(['West', 'Northeast']))
].sort_values('patient_satisfaction', ascending=False)

print("Final Analysis Report:")
display(final_report[['hospital_name', 'city', 'region', 'bed_count', 'patient_satisfaction']])

Final Analysis Report:

,hospital_name,city,region,bed_count,patient_satisfaction
1,St. Mary Medical Center,Los Angeles,West,320,4.7
0,City General Hospital,New York,Northeast,450,4.2
4,University Medical Center,Phoenix,West,520,4.1
7,Metro General,San Diego,West,380,3.8

## 📊 Statistical Analysis on Merged Data
### 💡 ELI10: Grouped Stats
Grouping is like sorting your Halloween candy into piles. Once you have a pile for 'Chocolate' and a pile for 'Fruit', you can count which pile is bigger or which has the most pieces.

In [9]:
# Subtask 5.2: Regional Statistics

# Group by region and calculate mean/max bed counts and satisfaction
regional_stats = complete_data.groupby('region').agg({
    'bed_count': ['mean', 'max'],
    'patient_satisfaction': ['mean', 'count']
}).round(2)

# Flatten column names for readability
regional_stats.columns = ['_'.join(col).strip() for col in regional_stats.columns]

print("Regional Hospital Statistics:")
display(regional_stats)

# Find top hospital by patient satisfaction in each region
top_by_region = complete_data.loc[complete_data.groupby('region')['patient_satisfaction'].idxmax()]
print("\nTop rated hospital in each region:")
display(top_by_region[['region', 'hospital_name', 'patient_satisfaction']])

Regional Hospital Statistics:

,bed_count_mean,bed_count_max,patient_satisfaction_mean,patient_satisfaction_count
region,,,,
Midwest,680.00,680,3.9,1
Northeast,370.00,450,4.5,2
South,295.00,410,4.4,2
West,406.67,520,4.2,3

Top rated hospital in each region:

      region            hospital_name  patient_satisfaction
2    Midwest   Regional Health System                   3.9
5  Northeast        Memorial Hospital                   4.8
3      South       Community Hospital                   4.5
1       West  St. Mary Medical Center                   4.7

## 📋 Creating Summary Reports
### 💡 ELI10: Reporting
A report is a professional summary that answers big questions like "How many high-quality hospitals do we have?"

In [10]:
# Subtask 5.3: Automated Reporting Function

def generate_hospital_report(h_df, l_df):
    # 1. Merge
    merged = pd.merge(h_df, l_df, on='hospital_id')

    # 2. Filter (Satisfaction > 4.0)
    quality_df = merged[merged['patient_satisfaction'] > 4.0]

    # 3. Sort (By size)
    sorted_report = quality_df.sort_values('bed_count', ascending=False)

    # 4. Summary metrics
    metrics = {
        'Total Hospitals': len(merged),
        'High Quality': len(quality_df),
        'Avg Beds': merged['bed_count'].mean()
    }

    return sorted_report, metrics

# Generate and print the report
report, summary = generate_hospital_report(hospitals, locations)
print("--- QUALITY HOSPITAL REPORT ---")
for key, val in summary.items():
    print(f"{key}: {val:.1f}" if isinstance(val, float) else f"{key}: {val}")

display(report[['hospital_name', 'city', 'bed_count', 'patient_satisfaction']])

--- QUALITY HOSPITAL REPORT ---
Total Hospitals: 8
High Quality: 6
Avg Beds: 403.8

               hospital_name          city  bed_count  patient_satisfaction
4  University Medical Center       Phoenix        520                   4.1
0      City General Hospital      New York        450                   4.2
6      Sacred Heart Hospital   San Antonio        410                   4.3
1    St. Mary Medical Center   Los Angeles        320                   4.7
5          Memorial Hospital  Philadelphia        290                   4.8
3         Community Hospital       Houston        180                   4.5

## ✅ Verification
Check if you can do the following:
1. [x] Import pandas and create DataFrames.
2. [x] Use `&` and `|` for complex filtering.
3. [x] Sort by multiple columns with different directions.
4. [x] Merge two tables using `pd.merge()`.

## 🛠 Troubleshooting
*   **KeyError**: Double-check column name spelling. 'hospital_id' is different from 'Hospital_ID'.
*   **Value Error with &**: Always use parentheses: `(df['a'] > 1) & (df['b'] < 5)`.
*   **File Not Found**: Ensure you ran the code cell that creates the CSV files first!

## 📚 Key Takeaways
*   **Filtering** allows you to zoom in on data that matters.
*   **Sorting** helps find the 'best' or 'worst' records quickly.
*   **Merging** is essential for combining data from different sources (like CSVs, Databases).

### Conclusion
You've mastered the building blocks of data manipulation! These skills are used by data scientists every day to turn messy data into clear, actionable reports.