# 🚀 Lab 12: Getting Started with Pandas DataFrames

### 📘 Lab Overview
In this lab, you will learn the fundamentals of working with **Pandas DataFrames** in Python. A DataFrame is one of the most important data structures in data science because it allows you to organize, inspect, filter, and analyze tabular data easily.

You will begin by loading CSV data into DataFrames, then inspect their structure using useful built-in methods such as `.head()`, `.info()`, and `.describe()`. You will also learn how to access rows and columns using `.loc[]` and `.iloc[]`, and apply these skills to practical data exploration tasks using student and sales datasets.

### 🎯 Objectives
By the end of this lab, you will be able to:
*   Understand what Pandas DataFrames are and their importance in data analysis.
*   Load CSV data into Pandas DataFrames using the `read_csv()` function.
*   Inspect and explore DataFrame structure using `.head()`, `.info()`, and `.describe()` methods.
*   Access specific rows and columns using `.loc[]` and `.iloc[]` indexing methods.
*   Perform basic data exploration tasks on real-world datasets.
*   Apply fundamental DataFrame operations to analyze data effectively.

### 🧰 Prerequisites
*   Basic understanding of Python programming concepts (variables, functions, data types).
*   Familiarity with Python lists and dictionaries.
*   Basic understanding of CSV file format and structure.

### ⚙️ Environment Setup
This lab is designed to run fully inside **Google Colab**. Colab comes with Pandas pre-installed, so we can jump right in!

## 🛠 Task 1: Verify Python and Pandas Installation

**ELI10 Explanation:** Before we start building our data tables, we need to make sure our computer (the Colab runtime) has the right tools installed. We are checking for Python (the language) and Pandas (our data toolbox).

In [ ]:
import sys
import pandas as pd

# Subtask 1.1: Check Python Version
# We check this to ensure our environment meets the minimum requirement of 3.6+
print("Python version:", sys.version)

# Subtask 1.2: Verify Pandas Installation
# This tells us which version of the pandas library we are using
print(f"Pandas version: {pd.__version__}")

## 📥 Task 2: Loading CSV Files into DataFrames

**ELI10 Explanation:** Imagine a CSV file is just a text version of an Excel sheet. We are going to take that text and turn it into a 'DataFrame'—which is just a fancy name for a table that Python can understand and manipulate.

In [2]:
import pandas as pd
import numpy as np
from io import StringIO

# Subtask 2.1: Create Sample Dataset
# We use StringIO to simulate a physical CSV file directly in our code
students_csv = StringIO("""student_id,name,age,grade,subject,score
1,Alice Johnson,20,A,Math,95
2,Bob Smith,19,B,Math,87
3,Carol Davis,21,A,Science,92
4,David Wilson,20,B,Science,78
5,Emma Brown,19,A,English,88
6,Frank Miller,22,C,English,76
7,Grace Lee,20,B,Math,91
8,Henry Taylor,21,A,Science,85
9,Ivy Chen,19,A,English,94
10,Jack Anderson,20,B,Math,82
""")

# Subtask 2.3: Load CSV File into DataFrame
# read_csv() is the standard way to turn CSV data into a DataFrame
df = pd.read_csv(students_csv)

print("DataFrame loaded successfully!")
display(df)

DataFrame loaded successfully!

   student_id           name  age grade  subject  score
0           1  Alice Johnson   20     A     Math     95
1           2      Bob Smith   19     B     Math     87
2           3    Carol Davis   21     A  Science     92
3           4   David Wilson   20     B  Science     78
4           5     Emma Brown   19     A  English     88
5           6   Frank Miller   22     C  English     76
6           7      Grace Lee   20     B     Math     91
7           8   Henry Taylor   21     A  Science     85
8           9       Ivy Chen   19     A  English     94
9          10  Jack Anderson   20     B     Math     82

### Subtask 2.4: Understanding DataFrame Structure
**Key Concept:** A DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. Think of it as a spreadsheet or SQL table in Python.

In [3]:
# Check the type of the object to confirm it is a pandas DataFrame
print(f"Type of df: {type(df)}")

# Check the shape (rows, columns) to see the size of our data
print(f"Shape: {df.shape}")

# Check column names to see what variables we have
print(f"Columns: {df.columns.tolist()}")

# Check index to see how rows are labeled
print(f"Index: {df.index}")

Type of df: <class 'pandas.core.frame.DataFrame'>
Shape: (10, 6)
Columns: ['student_id', 'name', 'age', 'grade', 'subject', 'score']
Index: RangeIndex(start=0, stop=10, step=1)

## 🔍 Task 3: Inspecting Data Using DataFrame Methods

**ELI10 Explanation:** When you get a huge set of data, you don't want to look at all 1,000,000 rows at once. These tools let you peek at the top, the bottom, and get a quick 'health check' of your data.

In [4]:
# Subtask 3.1: Using .head() Method
# .head(n) allows us to preview the first n rows
print("First 5 rows (default):")
display(df.head())

print("\nFirst 3 rows:")
display(df.head(3))

# Subtask 3.2: Using .tail() Method
# .tail(n) allows us to preview the last n rows
print("\nLast 3 rows:")
display(df.tail(3))

First 5 rows (default):

   student_id           name  age grade  subject  score
0           1  Alice Johnson   20     A     Math     95
1           2      Bob Smith   19     B     Math     87
2           3    Carol Davis   21     A  Science     92
3           4   David Wilson   20     B  Science     78
4           5     Emma Brown   19     A  English     88

First 3 rows:

   student_id           name  age grade  subject  score
0           1  Alice Johnson   20     A     Math     95
1           2      Bob Smith   19     B     Math     87
2           3    Carol Davis   21     A  Science     92

Last 3 rows:

   student_id           name  age grade  subject  score
7           8   Henry Taylor   21     A  Science     85
8           9       Ivy Chen   19     A  English     94
9          10  Jack Anderson   20     B     Math     82

In [5]:
# Subtask 3.3: Using .info() Method
# This provides a technical summary, showing data types and missing values
print("DataFrame Info:")
df.info()

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  10 non-null     int64
 1   name        10 non-null     object
 2   age         10 non-null     int64
 3   grade       10 non-null     object
 4   subject     10 non-null     object
 5   score       10 non-null     int64
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

In [6]:
# Subtask 3.4: Using .describe() Method
# This calculates statistics like Mean, Min, and Max for numeric columns
print("Statistical Summary (Numeric Only):")
display(df.describe())

print("\nAll columns summary (Includes names/grades):")
display(df.describe(include='all'))

Statistical Summary (Numeric Only):

       student_id        age      score
count    10.00000  10.000000  10.000000
mean      5.50000  20.100000  86.800000
std       3.02765   0.994429   6.545567
min       1.00000  19.000000  76.000000
25%       3.25000  19.250000  82.750000
50%       5.50000  20.000000  87.500000
75%       7.75000  20.750000  91.750000
max      10.00000  22.000000  95.000000

All columns summary (Includes names/grades):

        student_id           name        age grade subject      score
count     10.00000             10  10.000000    10      10  10.000000
unique         NaN             10        NaN     3       3        NaN
top            NaN  Alice Johnson        NaN     A    Math        NaN
freq           NaN              1        NaN     5       4        NaN
mean       5.50000            NaN  20.100000   NaN     NaN  86.800000
std        3.02765            NaN   0.994429   NaN     NaN   6.545567
min        1.00000            NaN  19.000000   NaN     NaN  76.000000
25%        3.25000            NaN  19.250000   NaN     NaN  82.750000
50%        5.50000            NaN  20.000000   NaN     NaN  87.500000
75%        7.75000            NaN  20.750000   NaN     NaN  91.750000
max       10.00000            NaN  22.000000   NaN     NaN  95.000000

## 🧪 Task 4: Accessing Rows and Columns

**ELI10 Explanation:** This is like using your finger to point at a specific cell in a printed table. We can select just one column, a few specific rows, or even filter for specific people (like everyone with a score over 90).

In [7]:
# Subtask 4.1: Basic Column Access

# Method 1: Using column name as attribute (dot notation)
print("Names column (attribute access):")
print(df.name.head())

# Method 2: Using square brackets (standard way)
print("\nNames column (bracket access):")
print(df['name'].head())

# Method 3: Selecting multiple columns (pass a list of names)
print("\nMultiple columns (name, age, score):")
display(df[['name', 'age', 'score']])

Names column (attribute access):
0    Alice Johnson
1        Bob Smith
2      Carol Davis
3     David Wilson
4       Emma Brown
Name: name, dtype: object

Names column (bracket access):
0    Alice Johnson
1        Bob Smith
2      Carol Davis
3     David Wilson
4       Emma Brown
Name: name, dtype: object

Multiple columns (name, age, score):

            name  age  score
0  Alice Johnson   20     95
1      Bob Smith   19     87
2    Carol Davis   21     92
3   David Wilson   20     78
4     Emma Brown   19     88
5   Frank Miller   22     76
6      Grace Lee   20     91
7   Henry Taylor   21     85
8       Ivy Chen   19     94
9  Jack Anderson   20     82

In [8]:
# Subtask 4.2: Using .loc[] for Label-Based Selection

# Select row with index label 0
print("Row with index 0:")
print(df.loc[0])

# Select rows 0 to 2 and specific columns
print("\nSpecific rows (0-2) and columns (name, score):")
display(df.loc[0:2, ['name', 'score']])

Row with index 0:
student_id                1
name          Alice Johnson
age                      20
grade                     A
subject                Math
score                    95
Name: 0, dtype: object

Specific rows (0-2) and columns (name, score):

            name  score
0  Alice Johnson     95
1      Bob Smith     87
2    Carol Davis     92

In [9]:
# Subtask 4.3: Using .iloc[] for Position-Based Selection

# Select first 3 rows using integer positions
print("First 3 rows using .iloc:")
display(df.iloc[0:3])

# Select rows 0-2 and columns 1-3 by position
print("\nRows 0-2, columns 1-3:")
display(df.iloc[0:3, 1:4])

First 3 rows using .iloc:

   student_id           name  age grade  subject  score
0           1  Alice Johnson   20     A     Math     95
1           2      Bob Smith   19     B     Math     87
2           3    Carol Davis   21     A  Science     92

Rows 0-2, columns 1-3:

            name  age grade
0  Alice Johnson   20     A
1      Bob Smith   19     B
2    Carol Davis   21     A

In [10]:
# Subtask 4.4: Advanced Selection Examples

# Select rows where score > 90 (Filtering)
print("Students with score > 90:")
high_scorers = df.loc[df['score'] > 90]
display(high_scorers)

# Multiple conditions: Age 20 AND Grade A
print("\nStudents aged 20 with grade A:")
result = df.loc[(df['age'] == 20) & (df['grade'] == 'A')]
display(result)

Students with score > 90:

   student_id           name  age grade  subject  score
0           1  Alice Johnson   20     A     Math     95
2           3    Carol Davis   21     A  Science     92
6           7      Grace Lee   20     B     Math     91
8           9       Ivy Chen   19     A  English     94

Students aged 20 with grade A:

   student_id           name  age grade subject  score
0           1  Alice Johnson   20     A    Math     95

## 📊 Task 5: Practical Data Exploration Exercise

**ELI10 Explanation:** Now that you have the tools, let's act like a real Data Analyst! We will create a sales dataset and try to find out which products are making the most money.

In [11]:
# Subtask 5.1: Create a Larger Dataset
sales_csv = StringIO("""product_id,product_name,category,price,quantity_sold,sales_date,region
1,Laptop Pro,Electronics,1299.99,45,2024-01-15,North
2,Wireless Mouse,Electronics,29.99,120,2024-01-15,South
3,Office Chair,Furniture,199.99,67,2024-01-16,East
4,Smartphone X,Electronics,899.99,89,2024-01-16,West
5,Desk Lamp,Furniture,49.99,34,2024-01-17,North
6,Tablet Mini,Electronics,399.99,78,2024-01-17,South
7,Bookshelf,Furniture,149.99,23,2024-01-18,East
8,Headphones,Electronics,79.99,156,2024-01-18,West
9,Standing Desk,Furniture,299.99,12,2024-01-19,North
10,Keyboard Pro,Electronics,129.99,98,2024-01-19,South
11,Monitor 24inch,Electronics,249.99,67,2024-01-20,East
12,Coffee Table,Furniture,179.99,45,2024-01-20,West
13,Webcam HD,Electronics,89.99,87,2024-01-21,North
14,Filing Cabinet,Furniture,119.99,29,2024-01-21,South
15,Printer All-in-One,Electronics,199.99,56,2024-01-22,East
""")

# Subtask 5.2: Load and Explore
sales_df = pd.read_csv(sales_csv)

print("Sales Dataset Loaded!")
display(sales_df.head())

Sales Dataset Loaded!

,product_id,product_name,category,price,quantity_sold,sales_date,region
0,1,Laptop Pro,Electronics,1299.99,45,2024-01-15,North
1,2,Wireless Mouse,Electronics,29.99,120,2024-01-15,South
2,3,Office Chair,Furniture,199.99,67,2024-01-16,East
3,4,Smartphone X,Electronics,899.99,89,2024-01-16,West
4,5,Desk Lamp,Furniture,49.99,34,2024-01-17,North

In [12]:
# Subtask 5.3: Advanced Data Analysis

# 1. Find products with highest sales quantity
print("Top 5 products by quantity sold:")
top_products = sales_df.loc[:, ['product_name', 'quantity_sold']].sort_values('quantity_sold', ascending=False)
display(top_products.head())

# 2. Filtering by category
print("\nElectronics products:")
electronics = sales_df.loc[sales_df['category'] == 'Electronics']
display(electronics[['product_name', 'price', 'quantity_sold']])

Top 5 products by quantity sold:

      product_name  quantity_sold
7       Headphones            156
1   Wireless Mouse            120
9     Keyboard Pro             98
3     Smartphone X             89
12       Webcam HD             87

Electronics products:

          product_name    price  quantity_sold
0           Laptop Pro  1299.99             45
1       Wireless Mouse    29.99            120
3         Smartphone X   899.99             89
5          Tablet Mini   399.99             78
7           Headphones    79.99            156
9         Keyboard Pro   129.99             98
10      Monitor 24inch   249.99             67
12           Webcam HD    89.99             87
14  Printer All-in-One   199.99             56

In [13]:
# Subtask 5.4: Calculate Revenue
# We create a new column by multiplying price and quantity
sales_df['revenue'] = sales_df['price'] * sales_df['quantity_sold']

print("Products with calculated revenue:")
display(sales_df[['product_name', 'price', 'quantity_sold', 'revenue']].head())

# Category-wise revenue analysis using summing
electronics_revenue = sales_df.loc[sales_df['category'] == 'Electronics', 'revenue'].sum()
furniture_revenue = sales_df.loc[sales_df['category'] == 'Furniture', 'revenue'].sum()

print(f"\nElectronics total revenue: ${electronics_revenue:,.2f}")
print(f"Furniture total revenue: ${furniture_revenue:,.2f}")

Products with calculated revenue:

     product_name    price  quantity_sold   revenue
0      Laptop Pro  1299.99             45  58499.55
1  Wireless Mouse    29.99            120   3598.80
2    Office Chair   199.99             67  13399.33
3    Smartphone X   899.99             89  80099.11
4       Desk Lamp    49.99             34   1699.66

Electronics total revenue: $234,392.04
Furniture total revenue: $33,727.90

## 📊 Task 6: Common DataFrame Operations

**ELI10 Explanation:** Sometimes you want to see the most expensive items first (Sorting) or you only want to see items in a specific price range (Filtering).

In [14]:
# Subtask 6.1: Sorting Data
print("Sorted by price (ascending):")
display(sales_df.sort_values('price')[['product_name', 'price']].head())

# Subtask 6.2: Filtering Data with Multiple Conditions
print("\nProducts from East or West regions (using isin):")
regions_filter = sales_df.loc[sales_df['region'].isin(['East', 'West'])]
display(regions_filter[['product_name', 'region']])

Sorted by price (ascending):

      product_name   price
1   Wireless Mouse   29.99
4        Desk Lamp   49.99
7       Headphones   79.99
12       Webcam HD   89.99
13  Filing Cabinet  119.99

Products from East or West regions (using isin):

          product_name region
2         Office Chair   East
3         Smartphone X   West
6            Bookshelf   East
7           Headphones   West
10      Monitor 24inch   East
11        Coffee Table   West
14  Printer All-in-One   East

## ✅ Verification Checklist
Confirm you can do the following:
- [ ] Successfully imported Pandas.
- [ ] Created DataFrames from CSV data string.
- [ ] Used `.head()`, `.tail()`, `.info()`, and `.describe()`.
- [ ] Accessed columns and rows using `.loc[]` and `.iloc[]`.
- [ ] Filtered and sorted data.
- [ ] Created a derived `revenue` column.

## 🛠 Troubleshooting
*   **KeyError:** Check if the column name is spelled exactly right (including capitalization).
*   **FileNotFound:** In this lab, we use `StringIO` to avoid this, but in real life, check your file path!
*   **IndexError:** Ensure you aren't asking for row 100 in a table that only has 10 rows.

## 📚 Key Takeaways / What I Learned
*   **DataFrames are flexible:** They handle different types of data (numbers, text, dates) all in one table.
*   **Inspection is key:** Always use `.info()` and `.head()` before you start analyzing to see what you're working with.
*   **Pandas makes math easy:** You can perform calculations across thousands of rows instantly just by multiplying columns.

## 🏁 Conclusion
Great job! You've mastered the building blocks of Pandas. These skills—loading, inspecting, selecting, and calculating—are the foundation for everything in Data Science. Whether you are building a machine learning model or a business report, it all starts with a DataFrame.